name: First time automation

on: 
  push

jobs:
  testing:
    name: Run Tests
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract branch name
        id: extract_branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Greet to user
        run: echo 'Welcome to testing'

      - name: Testing setup
        run: |
          sudo apt update
          sudo apt install -y nodejs
          npm install

      - name: Create .env file
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env

      - name: Run tests
        run: npm test

  merge:
    name: Auto-Merge to Master
    needs: testing
    if: ${{ success() }}
    runs-on: ubuntu-latest
    env:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ secrets.PAT_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch origin

      - name: Merge tested branch
        run: |
          git checkout master
          git pull origin master
          git merge origin/${{ needs.testing.outputs.branch }}
          git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git HEAD:master
